### ISSUE TITLE
Loading the h5ad files from the release bucket incurs NAT Gateway cost

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/cellxgene-fargate#12]
A recent [cost spike in the platform-sc account](https://github.com/DataBiosphere/azul/issues/1675) was caused by containers continuously being stopped and replacements being started which caused continuous loading of the h5ad files from the release bucket. While we should avoid continually restarting containers, the release bucket is in the same region as the container so we should route that traffic intelligently to avoid being charged for it. Traffic within a region should always be free.

**Comment by hannes-ucsc** [comment]
Step 1 is to check if GET requests to the public S3 object URL (https://s3.amazonaws.com/release-files.data.humancellatlas.org/release-files/releases/2020-mar/2020-Mar-Diff-Fetal-Neuron-SS2_annotated_v1.seurat.h5ad) instead of he CF distribution URL (https://data.humancellatlas.org/release-files/releases/2020-mar/2020-Mar-Diff-Fetal-Neuron-SS2_annotated_v1.seurat.h5ad) are still being routed through the NAT gateway.

**Comment by nadove-ucsc** [comment]
Using the public s3 URL appears to still route data through the NAT gateway.

**Comment by nadove-ucsc** [comment]
The files are automatically decompressed when using the S3 URL (cellxgene works just the same with no changes besides the URL)

**Comment by nadove-ucsc** [comment]
@hannes-ucsc It appears that cellxgene CAN follow s3:// urls (it uses [fsspec](https://filesystem-spec.readthedocs.io/en/latest/)) but the server does not start start successfully when trying to load the matrix files through them. I suspect it may not be decompressing them. Additionally, AWS authentication is required for the URL to work. For these reasons, I have only tested locally, not on ECS, and therefore have not tested yet whether this incurs a NAT gateway cost.

Evidence: when provided with an s3 URL to a nonexistent object, cellxgene fails immediately and complains that the key is not accessible. When provided with an s3 URL to a large existing matrix file, it runs for 5 minutes before failing and complains about the file signature.

```
$ time docker run -v ~/.aws:/root/.aws -e AWS_PROFILE=hca-id $CELLXGENE_IMAGE:$CELLXGENE_VERSION launch s3://release-files.data.humancellatlas.org/release-files/releases/2020-mar/2020-Mar-Census-Adult-Immune-10x_annotated_v1.seurat.h5ad
[cellxgene] Starting the CLI...
[cellxgene] Loading data from 2020-Mar-Census-Adult-Immune-10x_annotated_v1.seurat.h5ad.
...
Error: Unable to open file (file signature not found) - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.

real    5m20.631s
user    0m0.051s
sys     0m0.069s

$ time docker run -v ~/.aws:/root/.aws -e AWS_PROFILE=hca-id $CELLXGENE_IMAGE:$CELLXGENE_VERSION launch s3://release-files.data.humancellatlas.org/release-files/releases/2020-mar/does_not_exist.h5ad
[cellxgene] Starting the CLI...
[cellxgene] Loading data from does_not_exist.h5ad.
...
Error: release-files.data.humancellatlas.org/release-files/releases/2020-mar/does_not_exist.h5ad - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.

real    0m3.896s
user    0m0.024s
sys     0m0.028s
```

**Comment by hannes-ucsc** [comment]
cellxgene-fargate is EOL.
