### ISSUE TITLE
Error when loading first March release `.h5ad`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/cellxgene-fargate#2]
Running 

`cellxgene launch --verbose https://data.humancellatlas.org/release-files/releases/2020-mar/2020-Mar-Atlas-Adult-Retina-10x_annotated_v1.seurat.h5ad --host=0.0.0.0 --port=5005`

gives

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                                                                                          @message                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2020-03-12 23:16:56.950 | [cellxgene] Starting the CLI...                                                                                                                                                                                            |
| 2020-03-12 23:16:56.962 | [cellxgene] Loading data from 2020-Mar-Atlas-Adult-Retina-10x_annotated_v1.seurat.h5ad.                                                                                                                                    |
| 2020-03-12 23:17:13.507 | /build/.venv/lib/python3.6/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace. |
| 2020-03-12 23:17:13.507 |   from pandas.core.index import RangeIndex                                                                                                                                                                                 |
| 2020-03-12 23:17:13.507 | Error: 'dict' object has no attribute 'dtype' - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.                                                                  |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by hannes-ucsc** [comment]
Could you take a look, @noah-aviel-dove? I'd like to know what aspect of the input file is causing this, if we can work around it in cellxgene or if the file needs to be fixed, or both.

**Comment by nadove-ucsc** [comment]
I'm having issues trying to run cellxgene. Having just pulled develop and sourced `environment`, `cellxgene-fargate/src/azul' is a broken link, and `cellxgene-fargate/submodules/azul` is an empty folder. Attempting to install requirements via `python3.6 -m pip install -Ur requreiments.dev.txt` fails with `Could not open requirements file: [Errno 2] No such file or directory: 'submodules/azul/requirements.dev.txt'`. Trying the same with `requirements.txt` fails with `Could not find a version that satisfies the requirement cellxgene==${CELLXGENE_VERSION} (from -r requirements.txt (line 1))`. I can investigate the issue in the meantime by manually installing the correct version but we should fix this.

**Comment by nadove-ucsc** [comment]
It is not a problem with the file. It seems to be related to the version of the dependencies.

**Comment by hannes-ucsc** [comment]
The broken symlink and empty submodules/azul will be fixed by using `--recurse-submodules` with clone or checkout. The README mentions that, but only for `git clone`. You are probably the only other person with a clone of that repo so I think that's ok.

**Comment by nadove-ucsc** [comment]
Fixed the submodule checkout but still having errors with the bash variable in the requirements file.

**Comment by hannes-ucsc** [comment]
Could you start from a fresh clone, following the instruction in the README to the letter?

**Comment by hannes-ucsc** [comment]
Confirmed fixed. Thank you.

**Comment by hannes-ucsc** [comment]
Reopened so it can be mentioned during stand-up, to be closed after that.

@noah-aviel-dove, if you continue to have issues with the build, please open another issue. There was an issues with the build (408c47fb) but it was a different one. I can't reproduce your problem when I follow the instruction in the README.

**Comment by nadove-ucsc** [comment]
I had not noticed that the README had been so extensively edited. I suspect it was an issue with the version of `pip` I was using. Now a non-issue.
