### ISSUE TITLE
Provision task execution role

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/cellxgene-fargate#8]
The TF config currently assumes that an IAM role named `ecsTaskExecutionRole` exists in the target AWS account. This is because I had thought it already exists in every account which is not the case. It existed in the SC account because apparently the AWS console provisions it on demand when a user interactively creates a Fargate task. We should provision the role instead of discovering it via a TF [data source](https://github.com/DataBiosphere/cellxgene-fargate/blob/aaa3f831d90b0c12c7b000034bd81a799a363cc7/terraform/cellxgene.tf.json.template.py#L155).

**Comment by theathorn** [comment]
Demoed 4/14/20.
